"use strict";

const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("agentPet", {
    onState: (callback) => ipcRenderer.on("agent-state", (_event, snapshot) => callback(snapshot)),
    onDisplayMode: (callback) => ipcRenderer.on("display-mode", (_event, mode) => callback(mode)),
    onTypingActivity: (callback) => ipcRenderer.on("typing-activity", (_event, active) => callback(active)),
    onApprovalRequest: (callback) => ipcRenderer.on("approval-request", (_event, request) => callback(request)),
    onApprovalRequests: (callback) => ipcRenderer.on("approval-requests", (_event, requests) => callback(requests)),
    onWindowSettings: (callback) => ipcRenderer.on("window-settings", (_event, settings) => callback(settings)),
    onResourceUsage: (callback) => ipcRenderer.on("resource-usage", (_event, snapshot) => callback(snapshot)),
    onPositionAdjustMode: (callback) => ipcRenderer.on("position-adjust-mode", (_event, active) => callback(active)),
    onShowSessionDetails: (callback) => ipcRenderer.on("show-session-details", (_event, open) => callback(open)),
    onLocalSttUpdate: (callback) => ipcRenderer.on("local-stt-update", (_event, update) => callback(update)),
    onLocalSttRuntimeUpdate: (callback) => ipcRenderer.on("local-stt-runtime", (_event, update) => callback(update)),
    setDisplayMode: (mode) => ipcRenderer.send("set-display-mode", mode),
    decideApproval: (decision, requestId = null) => ipcRenderer.send("approval-decision", { decision, requestId }),
    dismissSession: (sessionId, force = false) => ipcRenderer.invoke("dismiss-session", { sessionId, force }),
    getHardwareMascotImage: () => ipcRenderer.invoke("hardware-mascot-image"),
    getHardwareMascotImages: () => ipcRenderer.invoke("hardware-mascot-images"),
    getLocalSttRuntimeStatus: () => ipcRenderer.invoke("local-stt-runtime-status"),
    retryLocalSttRuntime: () => ipcRenderer.invoke("local-stt-runtime-retry"),
    startLocalTranscription: (options = {}) => ipcRenderer.invoke("local-stt-start", options),
    appendLocalTranscriptionChunk: (chunk) => ipcRenderer.invoke("local-stt-chunk", chunk),
    finishLocalTranscription: () => ipcRenderer.invoke("local-stt-finish"),
    cancelLocalTranscription: () => ipcRenderer.invoke("local-stt-cancel"),
    clearLocalTranscription: () => ipcRenderer.invoke("local-stt-clear"),
    copyText: (value) => ipcRenderer.invoke("copy-text", value),
    clearFinishedSessions: () => ipcRenderer.send("clear-finished-sessions"),
    setSessionDetailsOpen: (open) => ipcRenderer.send("session-details-state", open),
    setTranscriptionPanelOpen: (open) => ipcRenderer.send("transcription-panel-state", true === open),
    setPointerHitState: (active) => ipcRenderer.send("pointer-hit-state", true === active),
    dragWindow: (dx, dy) => ipcRenderer.send("window-drag", dx, dy),
    hide: () => ipcRenderer.send("hide-window")
});
